Attendance_System/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Attendance_System.Controllers
{
    
    public class StudentController : Controller
    {
        // GET: Student/Student
        public ActionResult Index()
        {
            return View();
        }
    }
}

Attendance_System/Areas/Teacher/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Teacher Area</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/v4-shims.js"></script>
    @Styles.Render("~/Content/css")
</head>


<body class="skin-blue">

    <header class="main-header">
        <a class="logo">
            <span class="logo-lg"><b>AttendanceSystem</b></span>
        </a>
        <nav class="navbar navbar-static-top">
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </nav>
    </header>

    <!-- Sidepanel -->
    @Html.Partial("_Sidepanel")
    <!-- /Sidepanel -->
    <!-- Main Content -->
    <div class="content-wrapper">
        <div class="container">
            @RenderBody()
        </div>
    </div>

@Html.Partial("_Footer")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

Attendance_System/Areas/Teacher/Views/Shared/_SIdepanelTeacher.cshtml
@using Microsoft.AspNet.Identity


@{
    var hideClass = "";

    if (!Request.IsAuthenticated)
    {
        hideClass = "hide-me";
    }
    else
    {
        hideClass = "main-sidebar";
    }

    <!-- Left side column. contains the logo and sidebar -->
    <aside class="@hideClass">
        <section class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel">
                <div class="pull-left image">
                    I want to be Image
                </div>
                <div class="pull-left info">
                    <i class="fa fa-gears"></i>
                    @Html.ActionLink("Hello  " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                </div>
            </div>
            <!-- Sidebar Menu -->
            <ul class="sidebar-menu" data-widget="tree">
                <!-- Optionally, you can add icons to the links -->
                <li class="active"><a href="#"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
                @if (User.IsInRole("Admin"))
                {
                    <li><a class="logo" href="@Url.Action("Index", "Student", new { area = "" })"><i class="fa fa-users"></i>Students</a></li>
                }
                <li>
                <li><a class="logo" href="@Url.Action("Index", "Course", new { area = "" })"><i class="fa fa-book"></i>Courses</a></li></li>

            </ul>
            <!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>
}