Attendance_System/Areas/Admin/Controllers/LecturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Attendance_System.Models;

namespace Attendance_System.Areas.Admin.Controllers
{
    public class LecturesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Lectures
        public async Task<ActionResult> Index()
        {
            var lecture = db.Lecture.Include(l => l.Course);
            return View(await lecture.ToListAsync());
        }

        // GET: Admin/Lectures/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecture lecture = await db.Lecture.FindAsync(id);
            if (lecture == null)
            {
                return HttpNotFound();
            }
            return View(lecture);
        }

        // GET: Admin/Lectures/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName");
            return View();
        }

        // POST: Admin/Lectures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "LectureId,LectureName,Date,CourseId")] Lecture lecture)
        {
            if (ModelState.IsValid)
            {
                db.Lecture.Add(lecture);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName", lecture.CourseId);
            return View(lecture);
        }

        // GET: Admin/Lectures/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecture lecture = await db.Lecture.FindAsync(id);
            if (lecture == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName", lecture.CourseId);
            return View(lecture);
        }

        // POST: Admin/Lectures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "LectureId,LectureName,Date,CourseId")] Lecture lecture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lecture).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName", lecture.CourseId);
            return View(lecture);
        }

        // GET: Admin/Lectures/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecture lecture = await db.Lecture.FindAsync(id);
            if (lecture == null)
            {
                return HttpNotFound();
            }
            return View(lecture);
        }

        // POST: Admin/Lectures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Lecture lecture = await db.Lecture.FindAsync(id);
            db.Lecture.Remove(lecture);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Attendance_System/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Attendance_System.Models;

namespace Attendance_System.Controllers
{
    public class CoursesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Courses
        public async Task<ActionResult> Index()
        {
            return View(await db.Course.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = await db.Course.FindAsync(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CourseId,CourseName,Start,End")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Course.Add(course);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = await db.Course.FindAsync(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CourseId,CourseName,Start,End")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = await db.Course.FindAsync(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Course course = await db.Course.FindAsync(id);
            db.Course.Remove(course);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Attendance_System/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <p>@DateTime.Now.Year - Attendify - BAAA</p>
</footer>

Attendance_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Attendify</title>  
    <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/v4-shims.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")

</head>


<body class="skin-blue">  

    <div class="container">
        @RenderBody()
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/adminlte")
    @Scripts.Render("~/bundles/adminltedashboard")

    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(".datefield").datetimepicker({ format: 'yyyy-mm-dd hh:ii' });
    </script> 
    <script>
            $('.info-box.hvr-curl-top-left').hover(function () {
                $(this).addClass('magictime puffIn');
            });
    </script>
</body>

Attendance_System/Views/Shared/_Sidepanel.cshtml
@using Microsoft.AspNet.Identity  


@{ 
    var hideClass = "";


    if (!Request.IsAuthenticated)
    {
        hideClass = "hide-me";
    }
    else
    {
        hideClass = "main-sidebar";
    }


    var userImage = "";

    if (User.IsInRole("Admin"))
    {
        userImage = "admin.jpg";
    }
    else if (User.IsInRole("Teacher"))
    {
        userImage = "teacher.jpg";
    }
    else if (User.IsInRole("Student"))
    {
        userImage = "student.jpg";
    }


    <!-- Left side column. contains the logo and sidebar -->
    <aside class="@hideClass">
        <section class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img class="user-image" src="~/Content/@userImage" />
                </div>
                <div class="pull-left info">
                    <a href="~/Manage/Index">Hello @User.Identity.GetUserName()</a>
                </div>
            </div>
            <!-- Sidebar Menu -->
            <ul class="sidebar-menu" data-widget="tree">

                @if (User.IsInRole("Teacher"))
    {
            <li><a href="@Url.Action("Dashboard", "Dashboard", new { area = "Teacher" })"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>

}
                @if (User.IsInRole("Student"))
    {
            <li><a href="@Url.Action("Dashboard", "Dashboard", new { area = "Student" })"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
            <li><a href="@Url.Action("Index", "Course", new { area = "Student" })"><i class="fa fa-book"></i> <span>My Courses</span></a></li>
            <li><a href="@Url.Action("_StudentChart", "Dashboard", new { area = "Student" })"><i class="fa fa-stack-exchange"></i> <span>Statistics</span></a></li>
}

                @if (User.IsInRole("Admin"))
    {
            <li><a href="@Url.Action("Dashboard", "Dashboard", new { area = "Admin" })"><i class="fa fa-users"></i> <span>DashBoard</span></a></li>

            <li><a href="@Url.Action("Index", "Account", new { area = "Admin" })"><i class="fa fa-users"></i> <span>Users</span></a></li>

            <li><a href="@Url.Action("Index", "Courses", new { area = "Admin" })"><i class="fa fa-book"></i> <span>Courses</span></a></li>

            <li><a href="@Url.Action("Index", "Enrollments", new { area = "Admin" })"><i class="fa fa-graduation-cap"></i> <span>Enrollment</span></a></li>

            <li><a href="@Url.Action("Index", "Lectures", new { area = "Admin" })"><i class="fa fa-list-ul"></i> <span>Lecture</span></a></li>

            <li><a href="@Url.Action("_AdminChart", "Dashboard", new { area = "Admin" })"><i class="fa fa-stack-exchange"></i> <span>Statistics</span></a></li>
}
                @if (User.IsInRole("Teacher"))
    {
            <li><a href="@Url.Action("Index", "Course", new { area = "Teacher" })"><i class="fa fa-book"></i> <span>Courses</span></a></li>
            <li><a href="@Url.Action("Index", "Student", new { area = "Teacher" })"><i class="fa fa-users"></i> <span>Students</span></a></li>
            <li><a href="@Url.Action("_TeacherChart", "Dashboard", new { area = "Teacher" })"><i class="fa fa-stack-exchange"></i> <span>Statistics</span></a></li>
            <li><a href="@Url.Action("Index", "Lectures", new { area = "Teacher" })"><i class="fa fa-list-ul"></i> <span>Lectures</span></a></li>
}
            </ul>
            <!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>
}